
## Runtime configuration for the dcss_stats application.
##
core:
  logging: DEBUG
path: K:\Perso\dcss
# possible values : text,console,markdown
output: markdown
#path: C:\Temp
path: K:\Perso\dcss
scoreevol: False