
## Runtime configuration for the dcss_stats application.
##
core:
  logging: DEBUG
path: K:\Perso\dcss
# possible values : text,console,markdown,html
output: html
#path: K:\Perso\dcss
path: C:\Temp\braveplatypus2
#morgue_path: C:\Temp\braveplatypus2\morgue\_tt
scoreevol: False